package com.alexbalmus.euw.examples.bankaccounts.entities;

import java.util.Objects;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import org.hibernate.proxy.HibernateProxy;

import com.alexbalmus.euw.examples.bankaccounts.exceptions.BalanceException;


@Entity
@Table(name="account")
public class Account
{
    public static final String INSUFFICIENT_FUNDS = "Insufficient funds.";

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Long id;

    @Column(name = "balance")
    private Double balance;

    public Account(final Double balance)
    {
        this.balance = balance;
    }

    // Required by tests
    public Account(final Long id, final Double balance)
    {
        this.id = id;
        this.balance = balance;
    }

    // Required by ORM
    protected Account()
    {
    }

    public void increaseBalanceBy(final Double amount)
    {
        balance += amount;
    }

    public void decreaseBalanceBy(final Double amount)
    {
        if (balance < amount)
        {
            throw new BalanceException(INSUFFICIENT_FUNDS);
        }
        balance -= amount;
    }

    public Long getId()
    {
        return id;
    }

    public Double getBalance()
    {
        return balance;
    }


    // Generated by JPA Buddy:
    @Override
    public final boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }

        if (o == null)
        {
            return false;
        }

        Class<?> oEffectiveClass = o instanceof HibernateProxy
            ? ((HibernateProxy) o).getHibernateLazyInitializer().getPersistentClass()
            : o.getClass();

        Class<?> thisEffectiveClass = this instanceof HibernateProxy
            ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass()
            : this.getClass();

        if (thisEffectiveClass != oEffectiveClass)
        {
            return false;
        }

        Account account = (Account) o;

        return getId() != null && Objects.equals(getId(), account.getId());
    }

    // Generated by JPA Buddy:
    @Override
    public final int hashCode()
    {
        return this instanceof HibernateProxy
            ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass().hashCode()
            : getClass().hashCode();
    }
}

